(type $wabbit (struct
        (field $x (mut i32))
        (field $left (mut (ref null $wabbit)))
        (field $right (mut (ref null $wabbit)))
     ))
     (global $g (mut (ref null $wabbit)) (ref.null $wabbit))
     (func (export "init") (param $n i32)
       (global.set $g (call $make (local.get $n)))
     )
     (func $make (param $n i32) (result (ref null $wabbit))
       (local $tmp i32)
       (struct.new $wabbit (local.get $tmp) (ref.null $wabbit) (ref.null $wabbit))
     )